# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

script:
  - mvn test -B

env:
  global:
    - CODECOV_TOKEN="166a6ea3-12c4-48e7-9868-f97278403915"


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      bodins@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always


